# Generated by Django 5.0.6 on 2024-07-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Створене'), (1, 'Сплачене'), (3, 'Доставляється'), (2, 'Доставлено')], default=0),
        ),
    ]
